import { _MaterialItemStrict,_BrandPriority } from './types/materials'
import * as MyType from './types/materials'
/** 得到一个约束的列表类型,仅这里消费。因为外部会变动，不适合外部消费 */
type _MaterialsList = [
    _MaterialItemStrict<'沐浴露','瓶'>,
    _MaterialItemStrict<'洗发水','瓶'>,
    _MaterialItemStrict<'洗手液','瓶'>,
    _MaterialItemStrict<'矿泉水','瓶'>,
    _MaterialItemStrict<'牙膏','支'>,
    _MaterialItemStrict<'面巾纸','包'>,
    _MaterialItemStrict<'小垃圾袋','个'>,
    _MaterialItemStrict<'卷纸','卷'>,
    _MaterialItemStrict<'拖鞋','双'>,
    _MaterialItemStrict<'大垃圾袋','个'>,
    _MaterialItemStrict<'茶叶','袋'>,
    _MaterialItemStrict<'儿童拖鞋','双'>,
    _MaterialItemStrict<'牙具套餐','套'>,
    _MaterialItemStrict<'梳子','支'>,
    _MaterialItemStrict<'牙刷','支'>,
    _MaterialItemStrict<'咖啡','包'>
]

const SettlementNum = 120;
export const materialList:_MaterialsList = [
    {
        label:'沐浴露',
        list:[
            {
                label:'柠檬过江沐浴露',
                specs:[
                    {
                        unit:'箱',
                        spec:24
                    },
                    {
                        unit:'瓶',
                        spec:1
                    }
                ],
                priority:1
            }
        ],
        usage:{
            min:0,
            max:SettlementNum
        },
        baseAverageDayUse:3
    },
    {
        label:'洗发水',
        list:[
            {
                label:'柠檬过江洗发水',
                specs:[
                    {
                        unit:'箱',
                        spec:24
                    },
                    {
                        unit:'瓶',
                        spec:1
                    }
                ],
                priority:1
            }
        ],
        usage:{
            min:0,
            max:SettlementNum
        },
        baseAverageDayUse:3
    },
    {
        label:'洗手液',
        list:[
            {
                label:'柠檬过江洗手液',
                specs:[
                    {
                        unit:'箱',
                        spec:24
                    },
                    {
                        unit:'瓶',
                        spec:1
                    }
                ],
                priority:1
            }
        ],
        usage:{
            min:0,
            max:SettlementNum
        },
        baseAverageDayUse:1
    },
    {
        label:'矿泉水',
        list:[
            {
                label:'乐百氏矿泉水',
                specs:[
                    {
                        unit:'箱',
                        spec:24
                    },
                    {
                        unit:'瓶',
                        spec:1
                    }
                ],
                priority:1
            }
        ],
        usage:{
            min:0,
            max:SettlementNum * 5
        },
        baseAverageDayUse:320
    },
    {
        label:'牙膏',
        list:[
            {
                label:'美加净牙膏',
                specs:[
                    {
                        unit:'箱',
                        spec:500
                    },
                    {
                        unit:'支',
                        spec:1
                    }
                ],
                priority:1
            }
        ],
        usage:{
            min:0,
            max:SettlementNum * 2
        },
        baseAverageDayUse:145
    },
    {
        label:'面巾纸',
        list:[
            {
                label:'凤生面巾纸',
                specs:[
                    {
                        unit:'箱',
                        spec:60
                    },
                    {
                        unit:'包',
                        spec:1
                    }
                ],
                priority:2
            },
        ],
        usage:{
            min:0,
            max:SettlementNum
        },
        baseAverageDayUse:25
    },
    {
        label:'小垃圾袋',
        list:[
            {
                label:'白色垃圾袋',
                specs:[
                    {
                        unit:'扎',
                        spec:1000
                    },
                    {
                        unit:'个',
                        spec:1
                    }
                ],
                priority:1
            }
        ],
        usage:{
            min:0,
            max:SettlementNum * 3
        },
        baseAverageDayUse:150
    },
    {
        label:'卷纸',
        list:[
            {
                label:'凤生卷纸',
                specs:[
                    {
                        unit:'包',
                        spec:10
                    },
                    {
                        unit:'提',
                        spec:12
                    },
                    {
                        unit:'卷',
                        spec:1
                    }
                ],
                priority:2
            }
        ],
        usage:{
            min:0,
            max:SettlementNum * 2
        },
        baseAverageDayUse:40
    },
    {
        label:'拖鞋',
        list:[
            {
                label:'真美布拖鞋',
                specs:[
                    {
                        unit:'包',
                        spec:500
                    },
                    {
                        unit:'双',
                        spec:1
                    }
                ],
                priority:1
            }
        ],
        usage:{
            min:0,
            max:SettlementNum * 2
        },
        baseAverageDayUse:140
    },
    {
        label:'大垃圾袋',
        list:[
            {
                label:'黑色垃圾袋',
                specs:[
                    {
                        unit:'包',
                        spec:20
                    },
                    {
                        unit:'扎',
                        spec:50
                    },
                    {
                        unit:'个',
                        spec:1
                    }
                ],
                priority:1
            }
        ],
        usage:{
            min:0,
            max:SettlementNum * 2
        },
        baseAverageDayUse:32
    },
    {
        label:'茶叶',
        list:[
            {
                label:'神叶红茶',
                specs:[
                    {
                        unit:'箱',
                        spec:50
                    },
                    {
                        unit:'盒',
                        spec:50
                    },
                    {
                        unit:'袋',
                        spec:1
                    }
                ],
                priority:1
            }
        ],
        usage:{
            min:0,
            max:SettlementNum
        },
        baseAverageDayUse:42
    },
    {
        label:'儿童拖鞋',
        list:[
            {
                label:'真美布儿童拖鞋',
                specs:[
                    {
                        unit:'包',
                        spec:300
                    },
                    {
                        unit:'双',
                        spec:1
                    }
                ],
                priority:1
            }
        ],
        usage:{
            min:0,
            max:SettlementNum * 2
        },
        baseAverageDayUse:1
    },
    {
        label:'牙具套餐',
        list:[
            {
                label:'两面针牙具套餐',
                specs:[
                    {
                        unit:'箱',
                        spec:250
                    },
                    {
                        unit:'套',
                        spec:1
                    }
                ],
                priority:1
            }
        ],
        usage:{
            min:0,
            max:SettlementNum * 2
        },
        baseAverageDayUse:0
    },
    {
        label:'梳子',
        list:[
            {
                label:'秸秆香蕉梳',
                specs:[
                    {
                        unit:'箱',
                        spec:500
                    },
                    {
                        unit:'支',
                        spec:1
                    }
                ],
                priority:1
            }
        ],
        usage:{
            min:0,
            max:SettlementNum * 2
        },
        baseAverageDayUse:56
    },
    {
        label:'牙刷',
        list:[
            {
                label:'秸秆米白牙刷',
                specs:[
                    {
                        unit:'箱',
                        spec:500
                    },
                    {
                        unit:'支',
                        spec:1
                    }
                ],
                priority:1
            },
            {
                label:'秸秆浅灰牙刷',
                specs:[
                    {
                        unit:'箱',
                        spec:500
                    },
                    {
                        unit:'支',
                        spec:1
                    }
                ],
                priority:1
            }
        ],
        usage:{
            min:0,
            max:SettlementNum * 2
        },
        baseAverageDayUse:150
    },
    {
        label:'咖啡',
        list:[
            {
                label:'隅田川咖啡',
                specs:[
                    {
                        unit:'箱',
                        spec:250
                    },
                    {
                        unit:'包',
                        spec:1
                    }
                ],
                priority:1
            }
        ],
        usage:{
            min:0,
            max:SettlementNum
        },
        baseAverageDayUse:35
    }
]

export const brandPriorityMap = {
    '1':'优先使用',
    '2':'次优先使用',
    '3':'最后使用'
} as const;
/** 约束brandPriorityMap包含了所有的 BrandPriority值 */
type _BrandPriorityMapCheck = {
    [key in _BrandPriority]:(typeof brandPriorityMap)[`${key}`]
}

declare module '@typeConfig' {
    /** config.materials */
   export type MaterialItem = MyType._MaterialItem;
   export type BrandItem = MyType._BrandItem;
   export type BrandItemAtEdit = MyType._BrandItemAtEdit;
   export type MaterialItemAtEdit = MyType._MaterialItemAtEdit
   export type BrandPriorityMap = typeof brandPriorityMap;
   function foo(): void;
}
