import {RecordItemBase,RecordItemFull,RecordItemComputed} from '@types'

const recordItemBase:RecordItemBase = {
    recordDate:'1',
    list:[
        {
            label:'儿童拖鞋',
            list:[
                {
                    label:'1',
                    system:[{
                        unit:'个',
                        num:1
                    }],
                    purchase:[{
                        unit:'个',
                        num:1
                    }],
                    repo:[{
                        unit:'个',
                        num:1
                    }],
                    repoExtra:[{
                        unit:'个',
                        num:1
                    }],
                }
            ]
        }
    ]
}

const recordItemFull:RecordItemFull = {
    recordDate:'',
    list:[
        {
            label:'儿童拖鞋',
            usage:{min:1,max:2},
            baseAverageDayUse:20,
            list:[
                {
                    label:'1',
                    priority:1,
                    specs:[{
                        unit:'个',
                        spec:1
                    }],
                    system:[{
                        unit:'个',
                        spec:1,
                        num:1
                    }],
                    purchase:[{
                        unit:'个',
                        spec:1,
                        num:1
                    }],
                    repo:[{
                        unit:'个',
                        spec:1,
                        num:1
                    }],
                    repoExtra:[{
                        unit:'个',
                        spec:1,
                        num:1
                    }],
                }
            ]
        }
    ]
}

const recordItemComputed:RecordItemComputed = {
    recordDate:'',
    list:[{
        label:'儿童拖鞋',
        usage:{min:1,max:2},
        baseAverageDayUse:20,
        list:[
            {
                label:'1',
                priority:1,
                computed:{
                    systemNum:1,
                    repoExtraNum:1,
                    purchaseNum:1,
                    repoNum:1
                },
                hooks:{
                    onPurchaseNumChange:[],
                    onRepoExtraNumChange:[],
                    onRepoNumChange:[],
                    onSystemNumChange:[]
                },
                specs:[{
                    unit:'个',
                    spec:1
                }],
                system:[{
                    unit:'个',
                    spec:1,
                    num:1
                }],
                purchase:[{
                    unit:'个',
                    spec:1,
                    num:1
                }],
                repo:[{
                    unit:'个',
                    spec:1,
                    num:1
                }],
                repoExtra:[{
                    unit:'个',
                    spec:1,
                    num:1
                }],
            }
        ],
        computed:{
            systemNum:1,
            repoExtraNum:1,
            repoNum:1,
            purchaseNum:1
        },
        chartData:{
            dayUse:'-',
            availableDay:0,
            averageDayUse:0,
            weekUseText:'',
            monthUseText:'',
            outSuggestRelax:'-',
            outSuggestRelaxText:'',
            outSuggestStrong:'-',
            outSuggestStrongText:'',
            purchaseSuggest:'-',
            purchaseSuggestText:''
        },
        onChartDataChange:[],
        hooks:{
            onPurchaseNumChange:[],
            onRepoExtraNumChange:[],
            onRepoNumChange:[],
            onSystemNumChange:[]
        }

    }]
}