export const materialsList = [
    {
        label:'抽纸',
        units:[
            {
                label:'箱',
                spec:60
            },
            {
                label:'包'
            }
        ],
        // 用量，给个范围，给出库提供
        dosage:{
            min:1,
            max:100
        }
    },
    {
        label:'卷纸',
        units:[
            {
                label:'包',
                spec:10
            },
            {
                label:'提',
                spec:12
            },
            {
                label:'卷',
            }
        ]
    },
    {
        label:'茶叶',
        units:[
            {
                label:'箱',
                spec:50
            },
            {
                label:'盒',
                spec:50
            },
            {
                label:'包',
            }
        ]
    },
    {
        label:'咖啡',
        units:[
            {
                label:'箱',
                spec:250
            },
            {
                label:'包'
            }
        ]
    },
    {
        label:'沐浴露',
        units:[
            {
                label:'箱',
                spec:24
            },
            {
                label:'瓶'
            }
        ]
    },
    {
        label:'洗发水',
        units:[
            {
                label:'箱',
                spec:24
            },
            {
                label:'瓶'
            }
        ]
    },
    {
        label:'洗手液',
        units:[
            {
                label:'箱',
                spec:24
            },
            {
                label:'瓶'
            }
        ]
    },
    {
        label:'拖鞋',
        units:[
            {
                label:'包',
                spec:500
            },
            {
                label:'双'
            }
        ]
    },
    {
        label:'拖鞋(小)',
        units:[
            {
                label:'包',
                spec:700
            },
            {
                label:'双'
            }
        ]
    },
    {
        label:'儿童拖鞋',
        units:[
            {
                label:'包',
                spec:300
            },
            {
                label:'双'
            }
        ]
    },
    {
        label:'儿童牙刷',
        units:[
            {
                label:'箱',
                spec:250
            },
            {
                label:'支'
            }
        ]
    },
    {
        label:'灰色牙刷',
        units:[
            {
                label:'箱',
                spec:500
            },
            {
                label:'支'
            }
        ]
    },
    {
        label:'米白牙刷',
        units:[
            {
                label:'箱',
                spec:500
            },
            {
                label:'支'
            }
        ]
    },
    {
        label:'梳子',
        units:[
            {
                label:'箱',
                spec:500
            },
            {
                label:'支'
            }
        ]
    },
    {
        label:'牙膏',
        units:[
            {
                label:'箱',
                spec:500
            },
            {
                label:'支'
            }
        ]
    },
    {
        label:'大垃圾袋',
        units:[
            {
                label:'包',
                spec:20
            },
            {
                label:'扎',
                spec:50
            },
            {
                label:'条'
            }
        ]
    },
    {
        label:'小垃圾袋',
        units:[
            {
                label:'扎',
                spec:1000
            },
            {
                label:'条'
            }
        ]
    },
    {
        label:'矿泉水',
        units:[
            {
                label:'箱',
                spec:24
            },
            {
                label:'瓶'
            }
        ]  
    }
]