export const materialsList = [
    {
        label:'沐浴露',
        specs:[
            {
                unit:'箱',
                spec:24
            },
            {
                unit:'瓶'
            }
        ]
    },
    {
        label:'洗发水',
        specs:[
            {
                unit:'箱',
                spec:24
            },
            {
                unit:'瓶'
            }
        ]
    },
    {
        label:'洗手液',
        specs:[
            {
                unit:'箱',
                spec:24
            },
            {
                unit:'瓶'
            }
        ]
    },
    {
        label:'乐百氏矿泉水',
        specs:[
            {
                unit:'箱',
                spec:24
            },
            {
                unit:'瓶'
            }
        ]  
    },
    {
        label:'美加净牙膏',
        specs:[
            {
                unit:'箱',
                spec:500
            },
            {
                unit:'支'
            }
        ]
    },
    {
        label:'纤纯抽纸',
        specs:[
            {
                unit:'箱',
                spec:60
            },
            {
                unit:'包'
            }
        ],
    },
    {
        label:'白色垃圾袋',
        specs:[
            {
                unit:'扎',
                spec:1000
            },
            {
                unit:'个'
            }
        ]
    },
    {
        label:'纤纯卷纸',
        specs:[
            {
                unit:'包',
                spec:10
            },
            {
                unit:'提',
                spec:12
            },
            {
                unit:'卷',
            },
        ]
    },
    {
        label:'QZD拖鞋',
        specs:[
            {
                unit:'包',
                spec:700
            },
            {
                unit:'双'
            }
        ]
    },
    {
        label:'黑色垃圾袋',
        specs:[
            {
                unit:'包',
                spec:20
            },
            {
                unit:'扎',
                spec:50
            },
            {
                unit:'条'
            }
        ]
    },
    {
        label:'真美布拖鞋',
        specs:[
            {
                unit:'包',
                spec:500
            },
            {
                unit:'双'
            }
        ]
    },
    {
        label:'神叶红茶',
        specs:[
            {
                unit:'箱',
                spec:50
            },
            {
                unit:'盒',
                spec:50
            },
            {
                unit:'包',
            }
        ]
    },
    {
        label:'儿童真美布拖鞋',
        specs:[
            {
                unit:'包',
                spec:300
            },
            {
                unit:'双'
            }
        ]
    },
    {
        label:'儿童牙具套餐',
        specs:[
            {
                unit:'箱',
                spec:250
            },
            {
                unit:'支'
            }
        ]
    },
    {
        label:'香蕉梳',
        specs:[
            {
                unit:'箱',
                spec:500
            },
            {
                unit:'支'
            }
        ]
    },
    {
        label:'秸秆色牙刷',
        specs:[
            {
                unit:'箱',
                spec:500
            },
            {
                unit:'支'
            }
        ]
    },
    {
        label:'秸秆浅灰牙刷',
        specs:[
            {
                unit:'箱',
                spec:500
            },
            {
                unit:'支'
            }
        ]
    },
    {
        label:'隅田川咖啡',
        specs:[
            {
                unit:'箱',
                spec:250
            },
            {
                unit:'包'
            }
        ]
    },
]